### ISSUE TITLE
question about the decoder of the ecvae

### ISSUE THREAD

**Issue by sunxin000** [haonan-yuan/EAGLE#1]
Hello, I read your nips 2023 paper and i am very interested, but I am confused about equation 8. The decoder of z, pω(z | e, y), is not in the loss function of equation (8), how can it be updated? Actually, the equation 8  seems to reconstruct y，then how the ecvae generate latent z?

**Comment by haonan-yuan** [comment]
Hi sunxin! Thanks for your questions about our work. We are so sorry for the typos in Eq. (8), which caused your confusion. We have re-submitted the revised camera-ready version to PCs, which may take some time to process, and the arXiv version has already been updated (https://arxiv.org/pdf/2311.11114.pdf). We really appreciate your effort in checking our work and welcome furthur discussions!

**Comment by haonan-yuan** [comment]
Hi sunxin! Thanks for your questions about our work. We are so sorry for the typos in Eq. (8), which caused your confusion. We have re-submitted the revised camera-ready version to PCs, which may take some time to process, and the arXiv version has already been updated (https://arxiv.org/pdf/2311.11114.pdf). We really appreciate your effort in checking our work and welcome further discussions!
